- hosts: web
  become: yes

  vars:
    tls_cert_path: /tmp/cert.pem   # or passed via --extra-vars
    tls_key_path: /tmp/key.pem

  tasks:
    - name: Create folder to server from
      file:
        path: /var/www/frontend
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0775

    # keeping these in case our ip gets scanned since our ingress allows any ip
    - name: Disable SSH password auth
      lineinfile:
        path: /etc/ssh/sshd_config # path to check
        regexp: '^#?PasswordAuthentication' # regex to find the line, whether it's commented out or not
        line: 'PasswordAuthentication no' # the line to replace it with (uncommented and set to no)
        validate: /usr/sbin/sshd -t -f %s # %s gets replaced with path to temp file
      notify: Restart sshd # only triggered if something changes

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        validate: /usr/sbin/sshd -t -f %s
      notify: Restart sshd

    - name: Ensure nginx is installed
      package:
        name: nginx
        state: present

    # sets up systemctl to ensure nginx starts on boot and is running now
    - name: Ensure nginx is enabled and started
      service:
        name: nginx
        enabled: true
        state: started

    - name: Ensure SSL directory exists
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Install cert
      copy:
        src: "{{ tls_cert_path }}"
        dest: /etc/nginx/ssl/cert.pem
        mode: 0600
      notify: Reload nginx

    - name: Install key
      copy:
        src: "{{ tls_key_path }}"
        dest: /etc/nginx/ssl/key.pem
        mode: 0600
      notify: Reload nginx

    - name: Deploy nginx server config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/pranavdumpa.conf
        mode: 0644
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart sshd
      service:
        name: sshd
        state: restarted
