- hosts: web
  become: yes

  vars:
    tls_cert_path: /tmp/cert.pem   # or passed via --extra-vars
    tls_key_path: /tmp/key.pem

  tasks:
    - name: Ensure SSL directory exists
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: root
        group: root
        mode: 0700
    
    # Nginx is already on there

    - name: Install cert
      copy:
        src: "{{ tls_cert_path }}"
        dest: /etc/nginx/ssl/cert.pem
        mode: 0600

    - name: Install key
      copy:
        src: "{{ tls_key_path }}"
        dest: /etc/nginx/ssl/key.pem
        mode: 0600

    - name: Deploy nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
